# Generated by Django 4.2.6 on 2023-10-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscharacteristics',
            name='production_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='год производства'),
        ),
    ]
