# Generated by Django 4.2.6 on 2023-10-21 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_goodscharacteristics_production_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='goodscharacteristics',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterModelOptions(
            name='goodsimage',
            options={'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товара'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='discounted_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='goodscharacteristics',
            name='goods',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chars', to='goods.goods', verbose_name='товар'),
        ),
    ]
